name: sync_pods

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  sync_pods:
    # Name the Job
    name: sync pods
    # Set the type of machine to run on
    runs-on: macos-10.15

    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: '12.0'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Flutter action
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.22.5'
#      - name: Setup flutter environment
#        run: |
#            echo 'export FLUTTER_HOME=$HOME/sdks/flutter' >> $BASH_ENV
#            echo 'export FLUTTER_ROOT=$FLUTTER_HOME' >> $BASH_ENV
#            echo 'export FLUTTER_VERSION=1.22.5' >> $BASH_ENV
#            echo 'export FLUTTER_CHANNEL=stable' >> $BASH_ENV
#            echo 'export PATH=$FLUTTER_HOME/bin:$FLUTTER_HOME/bin/cache/dart-sdk/bin:$PATH' >> $BASH_ENV
#
#      - name: Download flutter
#        run: |
#            mkdir -p $HOME/sdks
#            curl --retry 3 -L -o /tmp/flutter.zip https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/macos/flutter_macos_${FLUTTER_VERSION}-${FLUTTER_CHANNEL}.zip
#            unzip -q /tmp/flutter.zip -d $HOME/sdks
#            flutter config --enable-macos-desktop
#            flutter doctor
#            flutter precache --force --ios --android --macos

      - name: Run sync podfiles
        run: |
            ./scripts/sync_pods.sh
